### PR TITLE
button added to toggle closed captions

### PR DESCRIPTION
**Pull request by buzzbo**
This is my first pull request ever, so be gentle...

[Screenshot](https://i.imgur.com/ZRaNGVc.jpg)

### CODE REVIEW

**Comment by mmitch** [comment]
I'll merge this and re-add the language change feature afterwards.
Thanks for the patch!

If you can, please check out my branch afterwards (you should be able to pull from it) and check if everything still works :-)  I currently don't have any files with multiple audio tracks and/or subtitles at hand.

**Comment by buzzbo** [comment]
Awesome, thanks!

**Comment by buzzbo** [comment]
If I recall correctly, the key commands you had assigned to L+/L- were actually for audio up/audio down. That's why I changed those.

**Comment by mmitch** [comment]
Switching the audio was the plan of the original omxplayer-frontend author, I think :-)

This should support both audio and subtitle changes:
https://github.com/mmitch/omxplayer-frontend/commit/b33a6db289be8db63b3c15f17752fc0f3a96ae27

**Pull request merged**
